[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tucsenspec"
version = "0.1.0"
description = "Wrapper for TUCSEN scientific cameras (specifically tested on Dhyana 400BSI V3) aimed at Spectroscopic methids. Exposes convenient methods such as 'set region of interest' and 'acquisition time', and exports data as a numpy array."
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Sam Brooke", email = "sjbrooke1993@gmail.com" }]
keywords = ["imaging", "spectroscopy"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: Windows", # Linux available on request 
]

# Runtime deps
dependencies = [
  "numpy>=2.3.3",
 "PyQt5==5.15.11",
 "PyQt5-Qt5==5.15.2",
 "PyQt5_sip==12.17.0"
]

# Tell setuptools to find packages inside src/
[tool.setuptools.packages.find]
where = ["src"]
include = ["tucsenspec*"]

[tool.setuptools_scm]
version_scheme = "post-release"

# If you need to ship non-.py files (DLLs, data, etc.)
[tool.setuptools.package-data]
yourpkg = ["lib/*.*"]
